env:
  es6:     true
  browser: true
  node:    true
  mocha:   true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended' 
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  no-new: 0
  no-console: 0
  no-var: 2
  strict: 0
  indent:
    - error
    - tab
  semi:
    - error
    - never
plugins:
  - html
  - vue
